### ISSUE TITLE
Images are cutting off

### ISSUE THREAD

**Issue by vbitzer** [GSA/centers-of-excellence#205]
Help! https://coe.gsa.gov/about/team.html Some images are cutting folks' heads off; yes I've tried to resize them :-/

**Comment by hbillings** [comment]
This is unfortunately an artifact of everyone's photo being so different. The photos are centered in the square, so when folks' faces aren't centered in their photos, it's going to cut off their foreheads or chins. It was less noticeable when the images were circles, because that shape accommodates human faces better, and having parts of the face cut off felt like more of an artistic choice. The fix for this is, unfortunately, standard photos. :-/
